--- 
intervals:
  - label: Baseline
    time: 10
    playSound: true
    instructions: |
      <p><b>SAY</b>: Nå skal du sitte sitte rolig i fem minutter uten å snakke, prøv å slappe av i kroppen og sitte så
      rolig som du klarer. Det kommer et kort pip når vi starter de fem minuttene og to korte pip når vi
      slutter. Er du klar? (start oppgaven hvis personen sier den er klar)</p>

      <p><b>DO</b>: <em>Testleder trykker START/ENTER for å starte baselineopptak på 5 minutter.</em></p>

      <p><b>WHAT THE PROGRAM DOES</b>: gives a PEEP when testleader hits button after instructions. Makes a
      timed event for this PEEP. Makes another TWO PEEPs after 5 minutes which ends the baseline.</p>
    pauseBefore:
      type: wait
  - label: Condition
    time: 30
    playSound: true
    pauseBefore:
      type: wait
    inputMatcher: "([0-9]+)[\n\r]"
    instructions: |
      <p><b>SAY</b>: Nå skal vi gjøre en telleoppgave der det fortsatt er viktig at du sitter rolig. Du skal ikke snakke nå
      heller. Når oppgaven starter vil jeg at du teller ned fra et tall med 7 om gangen, så fort du klarer. Du
      skal taste inn svaret på tastaturet her og trykke enter, og så neste svar og enter, neste svar og enter
      og så videre, jeg følger med på svarene her bak. Det kommer et kort pip når vi starter og to korte pip
      når vi slutter. Så hvis vi teller nedover fra 2020 med 7 om ganger, hva er det første tallet?
      <em>(Sjekk at testperson får til oppgaven (svar 2013). hvis ikke, gi svaret.)</em>
      Og hva gjør du da? <em>(Sjekk at personen forstår at den skal taste tallet og enter og telle videre).</em>
      Når det piper starter du å telle nedover fra 2013, 7 om gangen helt til det piper to ganger. Er du klar?
      <em>(start oppgaven hvis personen sier den er klar)</em></p>
      
      <p><b>DO</b>: <em>Testleder trykker START/ENTER for et PIP som starter 5 minutters telleoppgave.</em></p>

      <p><b>WHAT THE PROGRAM DOES</b>: gives a PEEP when testleader hits button after instructions. Makes a
      timed event for this PEEP. Makes another TWO PEEPs after 5 minutes.</p>
  - label: Return
    time: 10
    playSound: true
    pauseBefore:
      type: wait
    instructions: |
      <p><b>SAY</b>: Nå skal du sitte sitte rolig en siste gang uten å snakke, prøv å slappe av i kroppen og sitte så mye i ro
      som du klarer. Det kommer et kort pip når vi starter og to korte pip når vi slutter.
      Er du klar?
      (start oppgaven hvis personen sier den er klar)</p>
      
      <p><b>DO</b>: <em>Testleder trykker START/ENTER for et PIP som starter 5 minutters recovery.</em></p>

      <p><b>WHAT THE PROGRAM DOES</b>: gives a PEEP when testleader hits button after instructions. Makes a
      timed event for this PEEP. Makes another TWO PEEPs after 5 minutes.</p>
randomizeIntervals: false
preSoundFile: "beep.wav"
postSoundFile: "beepbeep.wav"
introText: "This is the HRV condition"
studyLabel: "HRV"
resultsDir: "/Users/mtl/tmp/results"
instructions: |
      This is the HRV test
  
