conditionInterval:
  - 5
  - 8
  - 15
randomizeInterval: true
pauseInterval: 10
playSound: true
soundFile: "beep.wav"
introText: "This is the Interoception condition"
pauseInputMatcher: "([0-9]+)[\n\r]"